namespace Bitwarden.Server.Sdk.RestrictedDependencies.Analyzers.Tests;

/// <summary>
/// What the analyzer decides before any collaborator runs: whether the project is in scope at
/// all, and that generated code is analyzed like any other. An auto-generated header,
/// <c>[GeneratedCode]</c> or <c>generated_code = true</c> would otherwise be a one-line bypass of
/// the gate.
/// </summary>
public class RestrictedDependencyAnalyzerTests
{
    [Fact]
    public async Task OutOfScopeProject_ReportsNothing()
    {
        await new AnalyzerHarness(enabled: false)
            .WithService()
            .WithConsumer(SampleProjectFixture.Consumer)
            .RunAsync();
    }

    [Fact]
    public async Task AutoGeneratedHeader_DoesNotExemptTheFile()
    {
        await AnalyzerHarness.WithBaseline()
            .WithConsumer("""
                // <auto-generated />
                using Test;

                namespace Test;

                public class Consumer
                {
                    public Consumer(IUserService {|BW0005:userService|})
                    {
                    }
                }
                """)
            .RunAsync();
    }

    [Fact]
    public async Task GeneratedCodeAttribute_DoesNotExemptTheClass()
    {
        await AnalyzerHarness.WithBaseline()
            .WithConsumer("""
                using System.CodeDom.Compiler;
                using Test;

                namespace Test;

                [GeneratedCode("x", "1")]
                public class Consumer
                {
                    public Consumer(IUserService {|BW0005:userService|})
                    {
                    }
                }
                """)
            .RunAsync();
    }

    [Fact]
    public async Task GeneratedCodeEditorConfig_DoesNotExemptTheFile()
    {
        await AnalyzerHarness.WithBaseline()
            .WithAnalyzerConfig("/repo/src/Api/.editorconfig", "[*.cs]\ngenerated_code = true\n")
            .WithConsumer("""
                using Test;

                namespace Test;

                public class Consumer
                {
                    public Consumer(IUserService {|BW0005:userService|})
                    {
                    }
                }
                """)
            .RunAsync();
    }
}
