using System.CodeDom.Compiler;
using Microsoft.CodeAnalysis;

namespace Bitwarden.Server.Sdk.Features.Analyzers;

internal sealed record FlagKeyCollectionSpec
{
    public required HierarchyInfo Type { get; init; }
    public required EquatableArray<(string Name, string Value, Location Location)> Fields { get; init; }

    public static FlagKeyCollectionSpec? Create(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol targetType)
        {
            return null;
        }

        var stringType = context.SemanticModel.Compilation.GetSpecialType(SpecialType.System_String);

        var fields = targetType.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => (f.DeclaredAccessibility == Accessibility.Public
                || f.DeclaredAccessibility == Accessibility.Internal)
                && SymbolEqualityComparer.Default.Equals(f.Type, stringType)
                && f.IsConst)
            .Select(f => (f.Name, (string)f.ConstantValue!, f.Locations.First()))
            .ToArray();

        return new FlagKeyCollectionSpec
        {
            Type = HierarchyInfo.From(targetType),
            Fields = new EquatableArray<(string Name, string Value, Location Location)>(fields),
        };
    }

    public void Write(IndentedTextWriter writer)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine();

        if (Type.Namespace is not "")
        {
            writer.WriteLine($"namespace {Type.Namespace}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        for (var i = Type.Hierarchy.Count - 1; i>= 0; i--)
        {
            var type = Type.Hierarchy[i];
            writer.WriteLine($"partial {(type.IsRecord ? "record" : "class")} {type.QualifiedName}");
            writer.WriteLine("{");
            writer.Indent++;

            if (i == 0)
            {
                writer.WriteLine("public IReadOnlyCollection<string> GetKeys()");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine("return [");
                writer.Indent++;
                foreach (var field in Fields)
                {
                    writer.WriteLine($"\"{field.Value}\",");
                }
                writer.Indent--;
                writer.WriteLine("];");
                writer.Indent--;
                writer.WriteLine("}");
                writer.Indent--;
            }
        }

        for (var i = 0; i < Type.Hierarchy.Count; i++)
        {
            // Close types
            writer.Indent--;
            writer.WriteLine("}");
        }

        if (Type.Namespace is not "")
        {
            writer.Indent--;
            writer.Write("}");
        }
    }
}
