using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;

namespace Bitwarden.Server.Sdk.Features.Analyzers.Tests;

public class FeaturesGeneratorTests
{
    [Fact]
    public async Task NoNamespace_Works()
    {
        await RunAsync(
            """
            using Bitwarden.Server.Sdk.Features;

            [FlagKeyCollection]
            public class MyFlags
            {
                public const string Flag = "my-flag";
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            using System.Collections.Generic;

            partial class MyFlags
            {
                public static IReadOnlyCollection<string> GetKeys()
                {
                    return [
                        Flag,
                    ];
                }
            }

            """
        );
    }

    [Fact]
    public async Task WithNamespace_Works()
    {
        await RunAsync(
            """
            using Bitwarden.Server.Sdk.Features;

            namespace MyApp
            {
                [FlagKeyCollection]
                public class MyFlags
                {
                    public const string Flag = "my-flag";
                }
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            using System.Collections.Generic;

            namespace MyApp
            {
                partial class MyFlags
                {
                    public static IReadOnlyCollection<string> GetKeys()
                    {
                        return [
                            Flag,
                        ];
                    }
                }
            }
            """
        );
    }

    [Fact]
    public async Task MultipleFields_AllIncluded()
    {
        await RunAsync(
            """
            using Bitwarden.Server.Sdk.Features;

            namespace Test;

            [FlagKeyCollection]
            public class MyFlags
            {
                public const string FlagOne = "flag-one";
                public const string FlagTwo = "flag-two";
                public const string FlagThree = "flag-three";
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            using System.Collections.Generic;

            namespace Test
            {
                partial class MyFlags
                {
                    public static IReadOnlyCollection<string> GetKeys()
                    {
                        return [
                            FlagOne,
                            FlagTwo,
                            FlagThree,
                        ];
                    }
                }
            }
            """
        );
    }

    [Fact]
    public async Task NoFields_ReturnsEmptyCollection()
    {
        await RunAsync(
            """
            using Bitwarden.Server.Sdk.Features;

            namespace Test;

            [FlagKeyCollection]
            public class MyFlags
            {
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            using System.Collections.Generic;

            namespace Test
            {
                partial class MyFlags
                {
                    public static IReadOnlyCollection<string> GetKeys()
                    {
                        return [
                        ];
                    }
                }
            }
            """
        );
    }

    [Fact]
    public async Task RecordClass_UsesRecordKeyword()
    {
        await RunAsync(
            """
            using Bitwarden.Server.Sdk.Features;

            namespace Test;

            [FlagKeyCollection]
            public record MyFlags
            {
                public const string Flag = "my-flag";
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            using System.Collections.Generic;

            namespace Test
            {
                partial record MyFlags
                {
                    public static IReadOnlyCollection<string> GetKeys()
                    {
                        return [
                            Flag,
                        ];
                    }
                }
            }
            """
        );
    }

    [Fact]
    public async Task NestedClass_WrapsInOuterClass()
    {
        await RunAsync(
            """
            using Bitwarden.Server.Sdk.Features;

            namespace Test;

            public class Outer
            {
                [FlagKeyCollection]
                public class MyFlags
                {
                    public const string Flag = "my-flag";
                }
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            using System.Collections.Generic;

            namespace Test
            {
                partial class Outer
                {
                    partial class MyFlags
                    {
                        public static IReadOnlyCollection<string> GetKeys()
                        {
                            return [
                                Flag,
                            ];
                        }
                    }
                }
            }
            """
        );
    }

    [Fact]
    public async Task NonStringConstFields_ExcludedFromGetKeys()
    {
        await RunAsync(
            """
            using Bitwarden.Server.Sdk.Features;

            namespace Test;

            [FlagKeyCollection]
            public class MyFlags
            {
                public const string StringFlag = "my-flag";
                public const int IntFlag = 42;
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            using System.Collections.Generic;

            namespace Test
            {
                partial class MyFlags
                {
                    public static IReadOnlyCollection<string> GetKeys()
                    {
                        return [
                            StringFlag,
                        ];
                    }
                }
            }
            """
        );
    }

    [Fact]
    public async Task NonConstStringFields_ExcludedFromGetKeys()
    {
        await RunAsync(
            """
            using Bitwarden.Server.Sdk.Features;

            namespace Test;

            [FlagKeyCollection]
            public class MyFlags
            {
                public const string ConstFlag = "my-flag";
                public static readonly string ReadonlyFlag = "another-flag";
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            using System.Collections.Generic;

            namespace Test
            {
                partial class MyFlags
                {
                    public static IReadOnlyCollection<string> GetKeys()
                    {
                        return [
                            ConstFlag,
                        ];
                    }
                }
            }
            """
        );
    }

    private static readonly CSharpParseOptions _parseOptions = new(LanguageVersion.CSharp12);

    private async Task RunAsync([StringSyntax("C#")] string source, [StringSyntax("C#")] string generatedSource)
    {
        var projectName = $"FeaturesGeneratorTestProject-{Guid.NewGuid()}";
        var compilationOptions = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
            .WithNullableContextOptions(NullableContextOptions.Enable);

        var project = new AdhocWorkspace().CurrentSolution
            .AddProject(projectName, projectName, LanguageNames.CSharp)
            .WithCompilationOptions(compilationOptions)
            .WithParseOptions(_parseOptions);

        var dotNetDir = Path.GetDirectoryName(typeof(object).Assembly.Location);

        project = project
            .AddMetadataReference(MetadataReference.CreateFromFile(typeof(IFeatureService).Assembly.Location))
            .AddMetadataReference(MetadataReference.CreateFromFile(typeof(object).Assembly.Location))
            .AddMetadataReference(MetadataReference.CreateFromFile(Path.Join(dotNetDir, "System.Runtime.dll")));

        project = project
            .AddDocument("TestSource.cs", SourceText.From(source, Encoding.UTF8))
            .Project;

        var initialCompilation = await project.GetCompilationAsync(TestContext.Current.CancellationToken);

        if (initialCompilation is null)
        {
            Assert.Fail("Could not compile test project");
        }

        var initialDiagnostics = initialCompilation.GetDiagnostics(TestContext.Current.CancellationToken);

        if (initialDiagnostics.Length > 0)
        {
            Debug.WriteLine("Initial diagnostics:");
            foreach (var diagnostic in initialDiagnostics)
            {
                Debug.WriteLine(diagnostic.ToString());
            }
        }

        var generator = new FeaturesGenerator().AsSourceGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [generator],
            driverOptions: new GeneratorDriverOptions(IncrementalGeneratorOutputKind.None, trackIncrementalGeneratorSteps: true),
            parseOptions: _parseOptions
        );

        driver = driver.RunGeneratorsAndUpdateCompilation(initialCompilation, out var updatedCompilation, out var updatedDiagnostics, TestContext.Current.CancellationToken);

        if (updatedDiagnostics.Length > 0)
        {
            Assert.Fail("Updated compilation has diagnostics.");
        }

        var runResult = driver.GetRunResult();

        var singleResult = Assert.Single(runResult.Results);

        var singleGeneratedSource = Assert.Single(singleResult.GeneratedSources);

        new DefaultVerifier().EqualOrDiff(generatedSource, singleGeneratedSource.SourceText.ToString());
    }
}
