namespace Bitwarden.Server.Sdk.RestrictedDependencies;

/// <summary>
/// Source for the two attributes, and the name of the one a host discovers restricted types
/// by. The text is emitted into every analyzed compilation by the package's generator, so a
/// consuming project applies <c>[RestrictedDependency]</c> without referencing an assembly.
/// </summary>
public static class AttributeConstants
{
    /// <summary>
    /// Fully qualified display name of the attribute that marks a restricted type or member.
    /// </summary>
    public const string RestrictedDependencyAttributeName = "Bitwarden.Server.Sdk.RestrictedDependencies.RestrictedDependencyAttribute";

    /// <summary>
    /// Fully qualified display name of the attribute that excepts a site from a restriction.
    /// </summary>
    public const string RestrictedDependencyExceptionAttributeName = "Bitwarden.Server.Sdk.RestrictedDependencies.RestrictedDependencyExceptionAttribute";

    /// <summary>
    /// Hint name the generator adds <see cref="Text"/> under.
    /// </summary>
    public const string HintName = "RestrictedDependencyAttributes.g.cs";

    /// <summary>
    /// The attribute source emitted into every analyzed compilation.
    /// </summary>
    public const string Text = """
        // <auto-generated/>
        // Emitted by Bitwarden.Server.Sdk.RestrictedDependencies.
        #nullable enable

        namespace Bitwarden.Server.Sdk.RestrictedDependencies
        {
            /// <summary>
            /// Marks a type, or one of its members, whose use is budgeted by the restricted-dependency
            /// analyzer. The usage budget itself lives in the repository's committed baseline for the type.
            /// </summary>
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Class | global::System.AttributeTargets.Interface |
                global::System.AttributeTargets.Method | global::System.AttributeTargets.Property |
                global::System.AttributeTargets.Event,
                AllowMultiple = false, Inherited = false)]
            internal sealed class RestrictedDependencyAttribute : global::System.Attribute
            {
                /// <summary>
                /// Existing (baselined) uses may remain. False forbids every use.
                /// </summary>
                public bool AllowExistingUses { get; set; } = true;

                /// <summary>
                /// New uses may be added freely; they are tracked in reports but not gated.
                /// </summary>
                public bool AllowNewUses { get; set; }

                /// <summary>
                /// Ticket or cluster id printed in every diagnostic and report row.
                /// </summary>
                public string? Tracking { get; set; }

                /// <summary>
                /// Team or department that owns the dissolution.
                /// </summary>
                public string? Owner { get; set; }

                /// <summary>
                /// Member level: what a caller should use instead. Printed in BW0006.
                /// </summary>
                public string? Replacement { get; set; }

                /// <summary>
                /// Type level: no method, event or property may be added that is not already in
                /// the baseline. Fields, constructors and user-defined operators are not covered.
                /// </summary>
                public bool SealMembers { get; set; }

                /// <summary>
                /// Type level: no nested type may be added that is not already in the baseline.
                /// </summary>
                public bool SealNestedTypes { get; set; }

                /// <summary>
                /// Type level: no property may be added to the type or, together with
                /// SealNestedTypes, to its nested types.
                /// </summary>
                public bool SealProperties { get; set; }

                /// <summary>
                /// Repo-relative globs (forward slashes, CODEOWNERS style). Files under a matching path
                /// are exempt from every access-shape rule for this type.
                /// </summary>
                public string[]? AllowedPaths { get; set; }
            }

            /// <summary>
            /// A structured, owned, expiring exception to a restricted dependency. On a class it covers
            /// injection, locator, concrete-type and escape uses inside that class; on a member it covers
            /// restricted member uses inside that member.
            /// </summary>
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct |
                global::System.AttributeTargets.Method | global::System.AttributeTargets.Property |
                global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Event,
                AllowMultiple = true, Inherited = false)]
            internal sealed class RestrictedDependencyExceptionAttribute : global::System.Attribute
            {
                public RestrictedDependencyExceptionAttribute(global::System.Type restrictedType)
                {
                    RestrictedType = restrictedType;
                }

                public global::System.Type RestrictedType { get; }

                /// <summary>
                /// Team that carries the debt, e.g. "team-billing".
                /// </summary>
                public string? Owner { get; set; }

                /// <summary>
                /// Ticket or short reason.
                /// </summary>
                public string? Reason { get; set; }

                /// <summary>
                /// Date in yyyy-MM-dd form. After it, BW0011 warns until the site is fixed or the
                /// date is renewed.
                /// </summary>
                public string? Expires { get; set; }
            }
        }

        """;
}
