<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Bitwarden.Server.Sdk.RestrictedDependencies</RootNamespace>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageReadmeFile></PackageReadmeFile>
    <IsAotCompatible>false</IsAotCompatible>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PolySharp" Version="1.16.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Bitwarden.Server.Sdk.RestrictedDependencies.Tests" />
  </ItemGroup>

</Project>
