using System.Globalization;
using System.Text;

namespace Bitwarden.Server.Sdk.RestrictedDependencies;

/// <summary>
/// The committed usage budget for one restricted type, stored as one JSON document per type.
/// Generated by the consuming repository's tool, read by the analyzer, and diffed by
/// <c>BudgetRatchet</c>. Two runs on the same tree serialize byte-identically; there is
/// no timestamp or commit hash by design.
/// </summary>
public sealed class BudgetModel
{
    /// <summary>
    /// Creates a baseline document. Declared members and usages are sorted, so two documents built
    /// from the same data serialize identically whatever order they were collected in.
    /// </summary>
    /// <param name="type">Fully qualified metadata name of the restricted type.</param>
    /// <param name="declaredMembers">Documentation-comment ids of the members a sealed type may have.</param>
    /// <param name="usages">Every recorded use of the type.</param>
    public BudgetModel(string type, IEnumerable<string> declaredMembers, IEnumerable<BudgetEntry> usages)
    {
        Type = type;
        DeclaredMembers = Sorted(declaredMembers, (left, right) => string.CompareOrdinal(left, right));
        Usages = Sorted(usages, BudgetEntry.Compare);
    }

    /// <summary>
    /// Fully qualified metadata name of the restricted type, e.g. <c>Bit.Core.Services.IUserService</c>.
    /// </summary>
    public string Type { get; }

    /// <summary>
    /// Documentation-comment ids of the members a sealed type is allowed to have. Empty when the
    /// type is not sealed.
    /// </summary>
    public IReadOnlyList<string> DeclaredMembers { get; }

    /// <summary>
    /// Every recorded use of the type, in serialization order.
    /// </summary>
    public IReadOnlyList<BudgetEntry> Usages { get; }

    /// <summary>
    /// The file name the baseline for <paramref name="type"/> is stored under.
    /// </summary>
    /// <param name="type">Fully qualified metadata name of the restricted type.</param>
    /// <returns>The baseline's file name.</returns>
    public static string FileNameFor(string type) => type + ".json";

    /// <summary>
    /// Parses a baseline document.
    /// </summary>
    /// <param name="json">The document text.</param>
    /// <returns>The parsed baseline.</returns>
    /// <exception cref="FormatException">
    /// The JSON is malformed, a required field is missing or has the wrong shape, or two rows
    /// describe the same use.
    /// </exception>
    public static BudgetModel Parse(string json)
    {
        if (BudgetJsonSerializer.Parse(json) is not Dictionary<string, object?> root)
        {
            throw new FormatException("Baseline must be a JSON object.");
        }

        var type = RequireString(root, "type");
        var declared = new List<string>();
        foreach (var item in RequireArray(root, "declaredMembers"))
        {
            declared.Add(item as string ?? throw new FormatException("'declaredMembers' must contain only strings."));
        }

        var usages = new List<BudgetEntry>();
        var seen = new HashSet<(DependencyUsageType Kind, string? Member, string Project, string Site)>();
        foreach (var item in RequireArray(root, "sites"))
        {
            if (item is not Dictionary<string, object?> site)
            {
                throw new FormatException("'sites' must contain only objects.");
            }

            var kindToken = RequireString(site, "kind");
            if (!DependencyUsageTypeExtensions.TryParse(kindToken, out var kind))
            {
                throw new FormatException($"Unknown site kind '{kindToken}'.");
            }

            var member = site.TryGetValue("member", out var memberValue) ? memberValue as string : null;
            if (kind == DependencyUsageType.Member && member is null)
            {
                throw new FormatException("A 'member' site must name its member.");
            }

            var count = 1;
            if (site.TryGetValue("count", out var countValue))
            {
                // Range-checked rather than `checked`: an OverflowException here would escape
                // both callers, which catch only FormatException, and crash instead of reporting.
                count = countValue is long l && l > 0 && l <= int.MaxValue
                    ? (int)l
                    : throw new FormatException("'count' must be a positive integer.");
            }

            var tracked = false;
            if (site.TryGetValue("tracked", out var trackedValue))
            {
                tracked = trackedValue is bool flag
                    ? flag
                    : throw new FormatException("'tracked' must be a boolean.");
            }

            var project = RequireString(site, "project");
            var siteId = RequireString(site, "site");

            // The analyzer budgets a key by summing every row that matches it, while staleness is
            // checked one row at a time. A repeated row therefore raises the ceiling and still
            // looks satisfied row by row, leaving budget that can never be ratcheted back down.
            if (!seen.Add((kind, member, project, siteId)))
            {
                throw new FormatException($"Duplicate '{kindToken}' site '{siteId}' in project '{project}'.");
            }

            usages.Add(new BudgetEntry(kind, member, project, siteId, count, tracked));
        }

        return new BudgetModel(type, declared, usages);
    }

    /// <summary>
    /// Writes the document in its canonical layout: two-space indent, one site per line, LF line
    /// endings, trailing newline. <c>count</c> is written for every member row and for other rows
    /// only when it is not 1; <c>tracked</c> only when it is true, so a document with no
    /// tracked-only rows is byte-identical to one written before the field existed.
    /// </summary>
    /// <returns>The serialized document.</returns>
    public string Serialize()
    {
        var builder = new StringBuilder();
        builder.Append("{\n");
        builder.Append("  \"type\": ");
        BudgetJsonSerializer.WriteString(builder, Type);
        builder.Append(",\n");

        builder.Append("  \"declaredMembers\": ");
        if (DeclaredMembers.Count == 0)
        {
            builder.Append("[]");
        }
        else
        {
            builder.Append("[\n");
            for (var i = 0; i < DeclaredMembers.Count; i++)
            {
                builder.Append("    ");
                BudgetJsonSerializer.WriteString(builder, DeclaredMembers[i]);
                builder.Append(i < DeclaredMembers.Count - 1 ? ",\n" : "\n");
            }

            builder.Append("  ]");
        }

        builder.Append(",\n");

        builder.Append("  \"sites\": ");
        if (Usages.Count == 0)
        {
            builder.Append("[]");
        }
        else
        {
            builder.Append("[\n");
            for (var i = 0; i < Usages.Count; i++)
            {
                var usage = Usages[i];
                builder.Append("    { \"kind\": ");
                BudgetJsonSerializer.WriteString(builder, usage.Kind.ToToken());
                if (usage.Member is not null)
                {
                    builder.Append(", \"member\": ");
                    BudgetJsonSerializer.WriteString(builder, usage.Member);
                }

                builder.Append(", \"project\": ");
                BudgetJsonSerializer.WriteString(builder, usage.Project);
                builder.Append(", \"site\": ");
                BudgetJsonSerializer.WriteString(builder, usage.Site);
                if (usage.Kind == DependencyUsageType.Member || usage.Count != 1)
                {
                    builder.Append(", \"count\": ").Append(usage.Count.ToString(CultureInfo.InvariantCulture));
                }

                if (usage.Tracked)
                {
                    builder.Append(", \"tracked\": true");
                }

                builder.Append(i < Usages.Count - 1 ? " },\n" : " }\n");
            }

            builder.Append("  ]");
        }

        builder.Append("\n}\n");
        return builder.ToString();
    }

    private static IReadOnlyList<T> Sorted<T>(IEnumerable<T> source, Comparison<T> comparison)
    {
        var sorted = new List<T>(source);
        sorted.Sort(comparison);
        return sorted;
    }

    private static string RequireString(Dictionary<string, object?> obj, string name) =>
        obj.TryGetValue(name, out var value) && value is string s
            ? s
            : throw new FormatException($"'{name}' must be a string.");

    private static List<object?> RequireArray(Dictionary<string, object?> obj, string name) =>
        obj.TryGetValue(name, out var value) && value is List<object?> list
            ? list
            : throw new FormatException($"'{name}' must be an array.");
}
