using System.Collections.Immutable;
using Microsoft.CodeAnalysis.CSharp;

namespace Bitwarden.Server.Sdk.Database.Analyzers;

/// <summary>
/// Source text for the generated scaffold. The file skeleton is a raw string literal so it reads
/// like the code it produces; the parts that vary per provider are rendered separately and spliced
/// in already indented, since interpolation only indents a fragment's first line.
/// </summary>
public sealed partial class DatabaseSetupGenerator
{
    private static string Emit(
        AttributeInfo attr,
        MigrationData migrationData,
        ImmutableArray<ProviderSpec> providers,
        BuildProperties buildProperties) => $$"""
        // <auto-generated/>
        #nullable enable

        using System;
        using System.IO;
        using System.Threading.Tasks;
        using System.CommandLine;
        using System.CommandLine.Invocation;
        using Microsoft.EntityFrameworkCore;
        using Microsoft.EntityFrameworkCore.Design;
        using Microsoft.EntityFrameworkCore.Infrastructure;
        using Microsoft.EntityFrameworkCore.Storage;
        using Microsoft.Extensions.Configuration;
        using Microsoft.Extensions.DependencyInjection;
        using Bitwarden.Server.Sdk.Database;

        namespace {{attr.Ns}};

        #if !SQLSERVER_MIGRATOR_BUILD
        {{EmitEfCoreInfrastructure(attr, migrationData, providers)}}
        #endif // !SQLSERVER_MIGRATOR_BUILD

        {{EmitDiExtension(attr, providers, buildProperties)}}

        {{EmitCli(attr, providers, buildProperties.ProjectDir)}}

        // Entry point for the migration executable.
        internal static class Program
        {
            static Task<int> Main(string[] args) => {{attr.SchemaName}}MigrationProgram.RunAsync(args);
        }

        """;

    // Provider subcontexts, design-time factories, and the migrations-assembly dispatcher. Ends
    // with a newline so the #endif that follows it in the skeleton keeps its blank line.
    private static string EmitEfCoreInfrastructure(
        AttributeInfo attr,
        MigrationData migrationData,
        ImmutableArray<ProviderSpec> providers)
    {
        var migrationsAssembly = EmitMigrationsAssembly(attr, migrationData, providers) + "\n";

        // SQL Server is migrated by DbUp from hand-authored scripts, so it gets no subcontext and
        // no design-time factory — there is nothing for EF tooling to scaffold against.
        var scaffolded = providers.Where(p => p.Name != "SqlServer").ToImmutableArray();

        if (scaffolded.Length == 0)
            return migrationsAssembly;

        var subcontexts = string.Join("\n", scaffolded.Select(p =>
            $"internal sealed class {p.Name}Context(DbContextOptions<{p.Name}Context> o) : {attr.TypeName}(o);"));

        var factories = string.Join("\n\n", scaffolded.Select(p => EmitFactory(p.Name, attr.SchemaName)));

        return $$"""
        // Provider subcontexts are internal so EF Designer.cs files can reference
        // them via [DbContext(typeof(...))] at compile time.
        {{subcontexts}}

        // Design-time factories are file-scoped so EF tooling can find them by
        // reflection without adding to the assembly's public surface.
        {{factories}}

        {{migrationsAssembly}}
        """;
    }

    /// <summary>
    /// A C# string literal, quotes included. Values reaching the generated source come from
    /// attribute arguments and build properties, so a stray quote or backslash would otherwise
    /// emit source that doesn't compile.
    /// </summary>
    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string EmitFactory(string providerName, string schemaName) => providerName switch
    {
        "Sqlite" => EmitStandardFactory(
            "Sqlite",
            useCall: "UseSqlite(connectionString)",
            connectionStringKey: "Sqlite",
            defaultConnectionString: "Data Source=:memory:"),
        "PostgreSql" => EmitStandardFactory(
            "PostgreSql",
            useCall: "UseNpgsql(connectionString)",
            connectionStringKey: "PostgreSql",
            defaultConnectionString: $"Host=localhost;Database={schemaName}"),
        // MySql has no usable default: ServerVersion.AutoDetect needs a reachable server.
        "MySql" => $$"""
        file sealed class MySqlContextFactory : IDesignTimeDbContextFactory<MySqlContext>
        {
            public MySqlContext CreateDbContext(string[] args)
            {
                var connectionString = new ConfigurationBuilder()
                    .AddEnvironmentVariables()
                    .AddCommandLine(args)
                    .Build()
                    .GetConnectionString("MySql")
                    ?? throw new InvalidOperationException(
                        "Set ConnectionStrings__MySql before running EF tools against {{schemaName}}.");
                return new MySqlContext(new DbContextOptionsBuilder<MySqlContext>()
                    .UseMySql(connectionString, ServerVersion.AutoDetect(connectionString)).Options);
            }
        }
        """,
        _ => "",
    };

    private static string EmitStandardFactory(
        string providerName,
        string useCall,
        string connectionStringKey,
        string defaultConnectionString) => $$"""
        file sealed class {{providerName}}ContextFactory : IDesignTimeDbContextFactory<{{providerName}}Context>
        {
            public {{providerName}}Context CreateDbContext(string[] args)
            {
                var connectionString = new ConfigurationBuilder()
                    .AddEnvironmentVariables()
                    .AddCommandLine(args)
                    .Build()
                    .GetConnectionString("{{connectionStringKey}}") ?? "{{defaultConnectionString}}";
                return new {{providerName}}Context(new DbContextOptionsBuilder<{{providerName}}Context>().{{useCall}}.Options);
            }
        }
        """;

    private const string EntryType =
        "(string Id, global::System.Reflection.TypeInfo Info, " +
        "global::System.Func<global::Microsoft.EntityFrameworkCore.Migrations.Migration> Factory)";

    private const string SnapshotType =
        "global::Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot?";

    private static string EmitMigrationsAssembly(
        AttributeInfo attr,
        MigrationData migrationData,
        ImmutableArray<ProviderSpec> providers)
    {
        // SQL Server has no EF migrations to hand out, and the dispatcher refuses it outright
        // rather than reporting an empty set, so Database.Migrate() fails loudly instead of
        // silently applying nothing.
        var efProviders = providers.Where(p => p.Name != "SqlServer").ToImmutableArray();

        var entryArrays = string.Join("\n\n", efProviders.Select(p =>
        {
            var entries = string.Join("\n", GetMigrations(migrationData, p.Name).Select(entry =>
                $"""
                        ({Literal(entry.Id)},
                            global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::{entry.FqTypeName})),
                            static () => new global::{entry.FqTypeName}()),
                """.TrimEnd()));

            return $"    private static readonly {EntryType}[] _{LowerFirst(p.Name)}Entries =\n"
                 + "    [\n"
                 + (entries.Length > 0 ? entries + "\n" : "")
                 + "    ];";
        }));

        var snapshots = string.Join("\n", efProviders.Select(p =>
        {
            var fqn = GetSnapshot(migrationData, p.Name);
            var value = fqn is not null ? $"new global::{fqn}()" : "null";
            return $"    private static readonly {SnapshotType} _{LowerFirst(p.Name)}Snapshot = {value};";
        }));

        var entryDispatch = EmitProviderDispatch(providers, attr.SchemaName, p => $"_{LowerFirst(p.Name)}Entries");
        var snapshotDispatch = EmitProviderDispatch(providers, attr.SchemaName, p => $"_{LowerFirst(p.Name)}Snapshot");
        var unsupported =
            "        throw new InvalidOperationException(\n"
            + $"            $\"Provider {{provider}} is not supported by {attr.TypeName}.\");";

        var fields = string.Join(
            "\n\n",
            new[] { entryArrays, snapshots }.Where(section => section.Length > 0));
        if (fields.Length > 0)
            fields += "\n";

        return $$"""
        // Migrations assembly dispatcher, file-scoped since only Add{{attr.SchemaName}} below uses it.
        // Migration entries are emitted at compile time, so there's no runtime
        // type scanning or Activator.CreateInstance involved.
        file sealed class {{attr.SchemaName}}MigrationsAssembly(IDatabaseProvider provider)
            : MigrationsAssemblyBase(
                typeof({{attr.TypeName}}).Assembly,
                SelectEntries(provider.Name),
                SelectSnapshot(provider.Name))
        {
        {{fields}}
            private static {{EntryType}}[] SelectEntries(string provider)
            {
        {{entryDispatch}}
        {{unsupported}}
            }

            private static {{SnapshotType}} SelectSnapshot(string provider)
            {
        {{snapshotDispatch}}
        {{unsupported}}
            }
        }
        """;
    }

    private static string EmitProviderDispatch(
        ImmutableArray<ProviderSpec> providers,
        string schemaName,
        Func<ProviderSpec, string> field)
        => string.Join("\n", providers.Select(p => p.Name == "SqlServer"
            ? $"        if (provider == \"{p.Assembly}\")\n"
              + "            throw new InvalidOperationException(\n"
              + $"                \"{schemaName} migrates SQL Server with DbUp, not EF Core migrations. \"\n"
              + $"                + \"Use the {schemaName} migrator instead of DbContext.Database calls.\");"
            : $"        if (provider == \"{p.Assembly}\") return {field(p)};"));

    private static string EmitDiExtension(
        AttributeInfo attr,
        ImmutableArray<ProviderSpec> providers,
        BuildProperties buildProperties)
    {
        // Without the build property, fall back to the schema's own namespace — what the SDK's
        // default, $(RootNamespace).SqlServer, resolves to for a conventionally laid out project.
        var prefix = buildProperties.ScriptPrefix ?? $"{attr.Ns}.SqlServer";

        var constants = $"    private const string ScriptPrefix = {Literal(prefix)};";
        var assignments = "            o.ScriptPrefix = ScriptPrefix;";

        if (buildProperties.PreviousScriptPrefix is { } previous)
        {
            constants +=
                "\n    // Prefix this schema's journal may still record, from BitPreviousSqlServerScriptPrefix.\n"
                + $"    private const string PreviousScriptPrefix = {Literal(previous)};";
            assignments += "\n            o.PreviousScriptPrefix = PreviousScriptPrefix;";
        }

        var cases = string.Join("\n", providers.Select(p =>
            $"                    case DatabaseProvider.{p.Name}:\n" +
            $"                        builder.{ProviderUseCall(p.Name)};\n" +
            "                        break;"));

        return $$"""
        public static class {{attr.SchemaName}}ServiceCollectionExtensions
        {
            // Resource-name prefix the scripts were embedded under, from BitSqlServerScriptPrefix.
        {{constants}}

        #if SQLSERVER_MIGRATOR_BUILD
            /// <summary>Registers {{attr.SchemaName}} SQL Server migration services against the named options key {{Literal(attr.MigratorKey)}}.</summary>
            public static IServiceCollection Add{{attr.SchemaName}}(this IServiceCollection services)
            {
                services.Configure<SqlServerMigrationOptions>({{Literal(attr.MigratorKey)}}, o =>
                {
        {{assignments}}
                });
                return services.AddSqlServerDatabaseMigrator({{Literal(attr.MigratorKey)}}, typeof({{attr.TypeName}}).Assembly);
            }
        #else
            /// <summary>Registers {{attr.SchemaName}} migration services against the named options key {{Literal(attr.MigratorKey)}}.</summary>
            public static IServiceCollection Add{{attr.SchemaName}}(this IServiceCollection services)
            {
                services.Configure<SqlServerMigrationOptions>({{Literal(attr.MigratorKey)}}, o =>
                {
        {{assignments}}
                });
                return services.AddDatabase<{{attr.TypeName}}, {{attr.SchemaName}}MigrationsAssembly>({{Literal(attr.MigratorKey)}},
                    static (opts, builder) =>
                    {
                        switch (opts.Provider)
                        {
        {{cases}}
                            default:
                                throw new global::System.InvalidOperationException($"Provider {opts.Provider} is not supported by {{attr.SchemaName}}.");
                        }
                    });
            }
        #endif
        }
        """;
    }

    private static string EmitCli(
        AttributeInfo attr,
        ImmutableArray<ProviderSpec> providers,
        string? projectDir) => $$"""
        // CLI app: builds the System.CommandLine root command for the migration executable.
        #if SQLSERVER_MIGRATOR_BUILD
        {{EmitSqlServerCliApp(attr)}}
        #else
        {{EmitEfCoreCliApp(attr, providers, projectDir)}}
        #endif // SQLSERVER_MIGRATOR_BUILD

        // CLI entry point, called from this assembly's Program.cs.
        internal static class {{attr.SchemaName}}MigrationProgram
        {
            public static Task<int> RunAsync(string[] args)
                => {{attr.SchemaName}}MigrationApp.Build().InvokeAsync(args);
        }
        """;

    private static string EmitSqlServerCliApp(AttributeInfo attr) => $$"""
        file static class {{attr.SchemaName}}MigrationApp
        {
            public static RootCommand Build()
            {
                var connectionString = new Argument<string>("connection-string")
                {
                    Description = "SQL Server connection string",
                };
                var phase = new Option<MigrationPhase>(["-p", "--phase"])
                {
                    Description = "Script set to apply: Initial or Transition",
                };
                phase.SetDefaultValue(MigrationPhase.Initial);
                var dryRun = new Option<bool>(["-d", "--dry-run"])
                {
                    Description = "Print the scripts that would be applied without executing them",
                };
                var noTransaction = new Option<bool>(["--no-transaction"])
                {
                    Description = "Run without a transaction",
                };
                var root = new RootCommand
                {
                    connectionString,
                    phase,
                    dryRun,
                    noTransaction,
                };
                root.SetHandler(async ctx =>
                {
                    await DatabaseMigrationCli.RunSqlServerAsync(
                        ctx.ParseResult.GetValueForArgument(connectionString),
                        {{Literal(attr.MigratorKey)}},
                        services => services.Add{{attr.SchemaName}}(),
                        ctx.ParseResult.GetValueForOption(phase),
                        ctx.ParseResult.GetValueForOption(noTransaction),
                        ctx.ParseResult.GetValueForOption(dryRun));
                });
                return root;
            }
        }
        """;

    private static string EmitEfCoreCliApp(
        AttributeInfo attr,
        ImmutableArray<ProviderSpec> providers,
        string? projectDir)
    {
        var options = string.Join("\n", providers.Select(p =>
            $"        var {LowerFirst(p.Name)} = new Option<string?>(\"--{p.Name.ToLowerInvariant()}\")\n" +
            "        {\n" +
            $"            Description = \"{ProviderDescription(p.Name)}\",\n" +
            "        };"));

        var rootCommand = providers.Length > 0
            ? "        var root = new RootCommand\n"
              + "        {\n"
              + string.Join("\n", providers.Select(p => $"            {LowerFirst(p.Name)},")) + "\n"
              + "        };"
            : "        var root = new RootCommand();";

        var migrateCalls = string.Join("\n", providers.Select(p =>
            $"            await DatabaseMigrationCli.MigrateOneAsync(DatabaseProvider.{p.Name}, " +
            $"ctx.ParseResult.GetValueForOption({LowerFirst(p.Name)}), {Literal(attr.MigratorKey)}, " +
            $"services => services.Add{attr.SchemaName}());"));

        var efProviders = string.Join("\n", providers
            .Where(p => p.Name != "SqlServer")
            .Select(p =>
                $"            (\"{attr.Ns}.{p.Name}Context\", \"Migrations/{p.Name}\", \"{attr.Ns}.Migrations.{p.Name}\"),"));

        // Prefer the project directory the compiler handed us; escaping double quotes matters only
        // for paths that contain them, but costs nothing. Without it, navigate from the binary.
        var projectDirArgument = projectDir is not null
            ? $"                {Literal(projectDir)},"
            : "                Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, \"../../../\")),";

        return $$"""
        file static class {{attr.SchemaName}}MigrationApp
        {
            public static RootCommand Build()
            {
        {{options}}
        {{rootCommand}}
                root.SetHandler(async ctx =>
                {
        {{migrateCalls}}
                });

        #if DEBUG
                (string Context, string OutputDir, string Namespace)[] efProviders =
                [
        {{efProviders}}
                ];
                var addMigration = new Command("add-migration", "Scaffold a new EF Core migration");
                var migrationName = new Argument<string>("migration-name")
                {
                    Description = "Migration name",
                };
                addMigration.AddArgument(migrationName);
                addMigration.SetHandler(async ctx =>
                {
                    await DatabaseMigrationCli.AddMigrationsAsync(
                        ctx.ParseResult.GetValueForArgument(migrationName)!,
        {{projectDirArgument}}
                        efProviders);
                });
                root.AddCommand(addMigration);
        #endif // DEBUG
                return root;
            }
        }
        """;
    }
}
