name: Cut Release

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to cut release for
        required: true
        type: choice
        options:
          - Bitwarden.Server.Sdk
          - Bitwarden.Extensions.Configuration
      releaseType:
        description: Is this a major or minor release
        default: Minor
        type: choice
        options:
          - Major
          - Minor

jobs:
  create-release-branch:
    name: Do Something
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up .NET
        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4.1.0

      - name: Get Release Version
        id: version
        working-directory: 'extensions/${{ inputs.package }}/src'
        run: |
          CURRENT=$(dotnet msbuild --getProperty:Version)
          SHORT_VERSION=${CURRENT%.*}
          echo "SHORT_VERSION=$SHORT_VERSION" >> $GITHUB_OUTPUT

      - name: Truncate Version
        run: echo ${{ steps.version.outputs.SHORT_VERSION }}
