name: Pack and release

on:
  workflow_call:
    inputs:
      prerelease:
        type: boolean

jobs:
  release:
    name: Pack and trigger release
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    outputs:
      package: ${{ steps.parse-package.outputs.result }}
      version: ${{ steps.current-version.outputs.VERSION }}
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up .NET
        uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1

      - name: Parse package
        id: parse-package
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          _REF: ${{ github.ref }}
        with:
          result-encoding: string
          script: |
            const ref = process.env._REF;

            if (!ref.startsWith('refs/heads/')) {
              core.setFailed(`Unexpected ref: ${ref}`);
              return;
            }

            // Example: refs/heads/release/{packageName}/{version}
            //          0   /1    /2      /3            /4
            const refParts = ref.split('/');

            if (refParts.length < 4) {
              core.setFailed(`Not at least 4 parts split by forward slash: ${ref}`);
              return;
            }

            return refParts[3];

      - name: Pack
        run: dotnet build --configuration Release --property:"IsPreRelease=$IS_PRERELEASE"
        working-directory: "./extensions/${{ steps.parse-package.outputs.result }}/src"
        env:
          IS_PRERELEASE: ${{ inputs.prerelease }}

      - name: Get current version
        id: current-version
        run: echo "VERSION=$(dotnet msbuild -p:"IsPreRelease=$IS_PRERELEASE" --getProperty:Version)" >> "$GITHUB_OUTPUT"
        working-directory: "./extensions/${{ steps.parse-package.outputs.result }}/src"
        env:
          IS_PRERELEASE: ${{ inputs.prerelease }}

      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: packages
          path: |
            **/*.nupkg
            **/*.snupkg

      - name: Trigger release workflow
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          task: release-dotnet-extensions
          data: >
            {
              "package": "${{ steps.parse-package.outputs.result }}",
              "version": "${{ steps.current-version.outputs.VERSION }}",
              "branch": "${{ github.ref_name }}",
              "run_id": "${{ github.run_id }}",
              "prerelease": ${{ inputs.prerelease }}
            }

  bump-version:
    name: Bump version on release branch
    needs: release
    uses: bitwarden/dotnet-extensions/.github/workflows/version-bump.yml@main
    permissions:
      id-token: write
    with:
      type: ${{ inputs.prerelease && 'prerelease' || 'hotfix' }}
      package: ${{ needs.release.outputs.package }}
    secrets: inherit
