name: Perform prerelease

on:
  push:
    paths:
      - "release/*"

jobs:
  prerelease:
    name: Do prerelease
    uses: bitwarden/dotnet-extensions/.github/workflows/pack-and-release.yml@main
    with:
      prerelease: true
