name: Perform prerelease

on:
  push:
    branches:
      - "release/**"

jobs:
  prerelease:
    name: Do prerelease
    uses: ./.github/workflows/pack-and-release.yml
    with:
      prerelease: true
    secrets:
      publish-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
