name: Perform prerelease

on:
  push:
    branches:
      - "release/**"

jobs:
  prerelease:
    name: Do prerelease
    uses: bitwarden/dotnet-extensions/.github/workflows/pack-and-release.yml@main
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    with:
      prerelease: true
    secrets: inherit # Needed for Azure login IDs
