name: Perform prerelease

on:
  push:
    paths:
      - "release/*"

jobs:
  prerelease:
    name: Do prerelease
    runs-on: ubuntu-22.04
    steps:
      - name: Pack and release
        uses: bitwarden/dotnet-extensions/.github/workflows/pack-and-release.yml@main
        with:
          prerelease: true
