name: Perform prerelease

on:
  workflow_dispatch: {}

jobs:
  prerelease:
    name: Do prerelease
    uses: bitwarden/dotnet-extensions/.github/workflows/pack-and-release.yml@main
    with:
      prerelease: true
    secrets:
      publish-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
