name: Perform release

on:
  workflow_dispatch: {}

jobs:
  release:
    name: Do release
    uses: bitwarden/dotnet-extensions/.github/workflows/pack-and-release.yml@main
    with:
      prerelease: false
