name: Perform release

on:
  workflow_dispatch: {}

jobs:
  release:
    name: Do release
    uses: bitwarden/dotnet-extensions/.github/workflows/pack-and-release.yml
    with:
      prerelease: false
    secrets:
      publish-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
