name: Perform release

on:
  workflow_dispatch: {}

jobs:
  token:
    name: Get publish token
    runs-on: ubuntu-24.04
    outputs:
      app-token: ${{ steps.app-token.outputs.token }}
    steps:
      - name: Generate GH App token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ secrets.BW_GHAPP_ID }}
          private-key: ${{ secrets.BW_GHAPP_KEY }}

  release:
    name: Do release
    needs: token
    uses: bitwarden/dotnet-extensions/.github/workflows/pack-and-release.yml@main
    with:
      prerelease: false
    secrets:
      publish-token: ${{ needs.token.outputs.app-token }}
