name: Perform release

on:
  workflow_dispatch: {}

jobs:
  release:
    name: Do release
    uses: bitwarden/dotnet-extensions/.github/workflows/pack-and-release.yml@main
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    with:
      prerelease: false
    secrets: inherit # Needed for Azure login IDs
