name: Review issue

on:
  issues:
    types: [opened, reopened]

permissions: {}

jobs:
  review:
    name: Review
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
      issues: write

    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Review with Claude Code
        uses: anthropics/claude-code-action@a5528eec7426a4f0c9c1ac96018daa53ebd05bc4 # v1.0.7
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            REPO: ${{ github.repository }}
            ISSUE NUMBER: ${{ github.event.issue.number }}
            TITLE: ${{ github.event.issue.title }}
            BODY: ${{ github.event.issue.body }}
            AUTHOR: ${{ github.event.issue.user.login }}

            Analyze this new issue and:
            1. Determine if it's a bug report, feature request, or question
            2. Assess priority (critical, high, medium, low)
            3. Check if it duplicates existing issues

            Note: The code is already checked out in the current working directory.

            Post a comment of the analysis.

          claude_args: |
            --allowedTools "Bash(gh issue:*),Bash(gh search:*)"
