name: Start release
run-name: Starting release for ${{ inputs.package }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to release
        required: true
        type: choice
        options:
          - Bitwarden.Extensions.Configuration
          - Bitwarden.Server.Sdk
          - Bitwarden.Server.Sdk.Authentication
          - Bitwarden.Server.Sdk.Caching
          - Bitwarden.Server.Sdk.Features
          - Bitwarden.Server.Sdk.HealthChecks
          - Bitwarden.Server.Sdk.WebEssentials

permissions: {}

env:
  PACKAGE_DIRECTORY: "./extensions/${{ inputs.package }}"

jobs:
  start-release:
    name: Trigger release branch creation
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up .NET
        uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1

      - name: Get current version
        id: current-version
        run: echo "VERSION=$(dotnet msbuild --getProperty:Version)" >> "$GITHUB_OUTPUT"
        working-directory: "${{ env.PACKAGE_DIRECTORY }}/src"

      - name: Trigger cut release branch
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          task: cut-release-branch-dotnet-extensions
          data: '{"package": "${{ inputs.package }}", "version": "${{ steps.current-version.outputs.VERSION }}"}'

  bump-version:
    name: Bump version on main branch
    needs: start-release
    uses: bitwarden/dotnet-extensions/.github/workflows/version-bump.yml@main
    permissions:
      id-token: write
    with:
      type: ga
      package: ${{ inputs.package }}
    secrets: inherit
