name: Bump version

on:
  workflow_call:
    inputs:
      type:
        description: Type of release
        required: true
        type: string
      package:
        description: Package to release
        required: true
        type: string

jobs:
  version-bump:
    name: Bump version
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    outputs:
      package: ${{ inputs.package }}
      new-version: ${{ steps.version-bumper.outputs.NEW_VERSION }}

    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up .NET
        uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1

      - name: Bump version
        id: version-bumper
        shell: pwsh
        env:
          PACKAGE_NAME: ${{ inputs.package }}
          BUMP_TYPE: ${{ inputs.type }}
        run: |
          $NEW_VERSION=$(./scripts/UpdatePackageVersion.ps1 -PackageName $env:PACKAGE_NAME -BumpType $env:BUMP_TYPE)
          Write-Output "NEW_VERSION=$NEW_VERSION" >> $Env:GITHUB_OUTPUT

      - name: Upload modified files
        uses: bitwarden/gh-actions/upload-modified-files@main
        with:
          artifact_name: modified-files

      - name: Trigger protected branch update
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          task: update-repository
          data: '{"artifact_name": "modified-files", "target_branch": "${{ github.ref_name }}"}'
